### ISSUE TITLE
wrong calculation

### ISSUE THREAD

**Issue by sokool** [marge-apps/currency-conversion-for-livechat-inc#3]
![image](https://user-images.githubusercontent.com/4784286/49652687-135df180-fa33-11e8-8f6f-dc47abc4b51b.png)

**Comment by mariosant** [comment]
Thanks so much for reporting this @sokool! Could you please share a bit more information? I am not entirely sure what you were expecting to see.

**Comment by mariosant** [comment]
Closed by https://github.com/marge-apps/currency-conversion-for-livechat-inc/commit/102a193a0105a6758a0c1d0192d40dbe09b9f3aa

**Comment by mariosant** [comment]
Thanks again, @sokool! I have fixed this issue!
